# Reference: https://github.com/openshift/assisted-service/blob/master/deploy/podman/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
    POSTGRESQL_DATABASE: installer
    POSTGRESQL_PASSWORD: password
    POSTGRESQL_USER: admin
    DB_HOST: 127.0.0.1
    DB_PORT: 5432
    DB_USER: admin
    DB_PASS: password
    DB_NAME: installer
    AUTH_TYPE: "none"
    DEPLOY_TARGET: onprem
    SKIP_CERT_VERIFICATION: true
    DUMMY_IGNITION: false
    ENABLE_SINGLE_NODE_DNSMASQ: true
    DISK_ENCRYPTION_SUPPORT: true
    PUBLIC_CONTAINER_REGISTRIES: "quay.io,registry-proxy.engineering.redhat.com"
    IMAGE_SERVICE_BASE_URL: http://< HOST IP >:8888
    INSTALL_RH_CA: true
    SERVICE_BASE_URL: http://< HOST IP >:8090
    ASSISTED_SERVICE_SCHEME: http
    ASSISTED_SERVICE_HOST: 127.0.0.1:8090
    LISTEN_PORT: "8888"
    STORAGE: filesystem
    RELEASE_IMAGES: '[{"openshift_version":"4.15.6-scos-multi","cpu_architecture":"multi","cpu_architectures":["x86_64","arm64"],"url":"quay.io/lxheryer/scos-release:4.15.6-scos-multi","version":"4.15.6-scos-multi"}]'
    OS_IMAGES: '[{"openshift_version":"4.15","cpu_architecture":"x86_64","url":"https://devfun.s3.amazonaws.com/scos/builds/latest/x86_64/scos-415.9.202406251159-0-live.x86_64.iso","version":"415.9.202406251159-0"},{"openshift_version":"4.15","cpu_architecture":"arm64","url":"https://devfun.s3.amazonaws.com/scos/builds/latest/aarch64/scos-415.9.202406250755-0-live.aarch64.iso","version":"415.9.202406250755-0"}]'
    NTP_DEFAULT_SERVER: ""
    IPV6_SUPPORT: true
    HW_VALIDATOR_REQUIREMENTS: '[{"version":"default","master":{"cpu_cores":4,"ram_mib":16384,"disk_size_gb":120,"installation_disk_speed_threshold_ms":10,"network_latency_threshold_ms":100,"packet_loss_percentage":0},"worker":{"cpu_cores":2,"ram_mib":8192,"disk_size_gb":120,"installation_disk_speed_threshold_ms":10,"network_latency_threshold_ms":1000,"packet_loss_percentage":10},"sno":{"cpu_cores":8,"ram_mib":16384,"disk_size_gb":120,"installation_disk_speed_threshold_ms":10}}]'        
    INSTALLER_IMAGE: "quay.io/edge-infrastructure/assisted-installer-multi:latest"
    CONTROLLER_IMAGE: "quay.io/edge-infrastructure/assisted-installer-controller-multi:latest"
    AGENT_DOCKER_IMAGE: "quay.io/edge-infrastructure/assisted-installer-agent-multi:latest"
    ALLOW_INSTALLER_RELEASE_IMAGE_OVERRIDE: True
